go_library(
    name = "server",
    srcs = [
        "server.go",
        "task.go",
    ],
    deps = [
        "//api",
        "//cfg",
        "//third_party/go:org_golang_google_grpc",
    ],
    visibility = ["PUBLIC"],
)
